server:
  port: 8083

spring:
  datasource:
    url: jdbc:h2:mem:inventorydb
    driverClassName: org.h2.Driver
    username: sa
    password:

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
